export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_DOESNT_MATCH = 'AUTH_DOESNT_MATCH';

export const INVITE_FRIEND_START = 'INVITE_FRIEND_START';
export const INVITE_FRIEND_SUCCESS = 'INVITE_FRIEND_SUCCESS';
export const INVITE_FRIEND_FAIL = 'INVITE_FRIEND_FAIL';

export const ACCEPT_FRIEND_START = 'ACCEPT_FRIEND_START';
export const ACCEPT_FRIEND_SUCCESS = 'ACCEPT_FRIEND_SUCCESS';
export const ACCEPT_FRIEND_FAIL = 'ACCEPT_FRIEND_FAIL';

export const DECLINE_FRIEND_START = 'DECLINE_FRIEND_START';
export const DECLINE_FRIEND_SUCCESS = 'DECLINE_FRIEND_SUCCESS';
export const DECLINE_FRIEND_FAIL = 'DECLINE_FRIEND_FAIL';
