export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_DOESNT_MATCH = 'AUTH_DOESNT_MATCH';

export const INVITE_FRIEND_START = 'INVITE_FRIEND_START';
export const INVITE_FRIEND_SUCCESS = 'INVITE_FRIEND_SUCCESS';
export const INVITE_FRIEND_FAIL = 'INVITE_FRIEND_FAIL';

export const ACCEPT_FRIEND_START = 'ACCEPT_FRIEND_START';
export const ACCEPT_FRIEND_SUCCESS = 'ACCEPT_FRIEND_SUCCESS';
export const ACCEPT_FRIEND_FAIL = 'ACCEPT_FRIEND_FAIL';

export const DECLINE_FRIEND_START = 'DECLINE_FRIEND_START';
export const DECLINE_FRIEND_SUCCESS = 'DECLINE_FRIEND_SUCCESS';
export const DECLINE_FRIEND_FAIL = 'DECLINE_FRIEND_FAIL';


export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
// Data reducer types
export const SET_SCREAMS = 'SET_SCREAMS';
export const SET_SCREAM = 'SET_SCREAM';
export const LIKE_SCREAM = 'LIKE_SCREAM';
export const UNLIKE_SCREAM = 'UNLIKE_SCREAM';
export const DELETE_SCREAM = 'DELETE_SCREAM';
export const POST_SCREAM = 'POST_SCREAM';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
